name: Unit tests

on:
  push:
  pull_request:
    branches: [ main ]

env:
  PYTHON_DEFAULT_VERSION: "3.10"

jobs:
  unittest:
    name: Perform unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
